- name: "Hosts"
  hosts: all
  become: yes

  tasks:

  - name: "Docker-ce | ctop"
    get_url:
     url: https://github.com/bcicen/ctop/releases/download/v0.6.0/ctop-0.6.0-linux-amd64
     dest: /usr/local/bin/ctop
     mode: 0755